[package]
name = "interval_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.20.3", features = ["extension-module"] }

[lib]
name = "interval_manager"
crate-type = ["cdylib"]